version: '3.7'
services:
  postgres:
    image: postgres:13-alpine
    container_name: postgres_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 9mREsvXDs9Gk89Ef